//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManagementView
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string StreetNumber { get; set; }
        public string City { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Name { get; set; }
        public string Roles { get; set; }
        public string Id { get; set; }
    }
}
